services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ipmanager
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
