spring.application.name=ipManager
spring.profiles.active=local
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# DESABILITE Hibernate DDL - deixa só Flyway gerenciar schema
spring.jpa.hibernate.ddl-auto=none

# Configurações Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.database-type=postgresql
