spring.application.name=ipManager
spring.profiles.active=local

spring.datasource.url=jdbc:postgresql://localhost:5432/ipmanager
spring.datasource.username=test
spring.datasource.password=test
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.flyway.database-type=postgresql
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always
logging.level.root=INFO
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG