spring.application.name=ipManager
spring.profiles.active=local
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
server.port=${PORT:8080}
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.database-type=postgresql
front.url=${FRONT-END-CLIENT}
configuration.allowCredentials=true
server.servlet.session.cookie.same-site=${SESSION_COOKIE_SAME_SITE:none}
server.servlet.session.cookie.secure=${SESSION_COOKIE_SECURE:true}
